config/routes.rb
RedditClone::Application.routes.draw do
  # get "subs/new"
  # get "subs/edit"
  # get "subs/create"
  # get "subs/update"
  # get "subs/index"
  # get "subs/show"
  # get "subs/destroy"
  root to: 'users#index'
  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"
  # get "users/new"
  # get "users/create"
  resources :users, only: [:new, :create, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :comments
  resources :subs
  resources :links
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :link, presence: true

  belongs_to :link
  belongs_to :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id

  has_many :comments,
    class_name: 'Comment',
    foreign_key: :parent_comment_id,
    primary_key: :id
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, :url, :user, presence: true

  belongs_to :user
  has_many :link_subs
  has_many :comments
  has_many :subs, through: :link_subs

  def comments_by_parent_id
    link_comments = self.comments

    comment_hash = Hash.new { |h,v| h[v] = [] }
    link_comments.each do |link_comment|
      comment_hash[link_comment.parent_comment_id] << link_comment
    end
    comment_hash
  end
end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  validates :link, :sub, presence: true

  belongs_to :link
  belongs_to :sub
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :name, :moderator, presence: true

  belongs_to :moderator, class_name: "User", foreign_key: :moderator_id
  has_many :link_subs
  has_many :links, through: :link_subs
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  has_many :links
  has_many :comments

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(pt)
    self.password_digest = BCrypt::Password.create(pt)
  end

  def is_password?(pt)
    @password = pt
    BCrypt::Password.new(self.password_digest).is_password?(pt) unless pt.nil?
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  validates :user, :link, presence: true
  validates :upvote, inclusion: { in: [true, false] }

  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :get_auth_token

  include ApplicationHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment,
          notice: 'Comment was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment,
          notice: 'Comment was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :link_id, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @comments_hash = @link.comments_by_parent_id
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params[:link]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])

    if @user
      sign_in!(@user)
      redirect_to root_url
    else
      flash[:errors] = ["Invalid username/password"]
      redirect_to new_session_url
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new

  end

  def edit
  end

  def create
  end

  def update
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    #return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def sign_in!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def sign_out!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def signed_in?
    !!current_user
  end

  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end

  def get_auth_token
    "<input type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}' >".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul>
<%= this_comment.body %>

<% @comments_hash[this_comment.id].each do |child_c| %>

  <li>
    <%= render :partial => 'comments/comment', locals: {
        this_comment: child_c } %>
  </li>

<% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'comment', locals: {
    comment: @comments_hash[nil],
    comment_hash: @comments_hash } %>

    <%= @comments_hash[nil] %>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
    <% @comments_hash[nil].each do |comment| %>
      <%= render :partial => 'comments/comment', locals: { :this_comment => comment } %>
    <% end %>
</ul>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Subs#index</h1>
<p>Find me in app/views/subs/index.html.erb</p>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
users index

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>


<form action="<%= users_url %>" method="post" accept-charset="utf-8">
  <%= get_auth_token %>
  <label for="username">Username</label><input type="text" name="user[username]" value="" id="username">
  <label for="password">Password</label><input type="password" name="user[password]" value="" id="password">

  <p><input type="submit" value="Sign Up"></p>
</form>